"""add FEATURE_REQUESTED to notification_type enum

Revision ID: 4cf9dc03d72f
Revises: 6ac43038049c
Create Date: 2026-08-01 01:08:10.555606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf9dc03d72f'
down_revision: Union[str, Sequence[str], None] = '6ac43038049c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'FEATURE_REQUESTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
